### ISSUE TITLE
UI/UX

### ISSUE THREAD

**Issue by VuNguyen76** [VuNguyen76/Hair_Salon#2]

**Comment by VuNguyen76** [comment]
Dán link figma vào đây

**Comment by VuNguyen76** [comment]
[https://www.figma.com/](url)

**Comment by Trng-Ngyn** [comment]
Thiết kế Nhân viên quản lý:
https://www.figma.com/design/ZmOfR7UscLvGpSVGfD5vNO/Untitled?node-id=0-1&t=mL1j2y8OaAquZjSd-1

**Comment by Phongut05** [comment]
https://www.figma.com/design/jtwPb1dEnrW3mAYkRUIHeF/Untitled?node-id=0-1&t=UtFRwkhaskTXzmkH-1

**Comment by Phongut05** [comment]
thiết kế phần đặt lịch: 
https://www.figma.com/design/jtwPb1dEnrW3mAYkRUIHeF/Untitled?node-id=0-1&t=UtFRwkhaskTXzmkH-1
thiết kế dashboard:
https://www.figma.com/design/FUwxHUUYinAx09z0Nc5q5G/Untitled?node-id=0-1&t=UtFRwkhaskTXzmkH-1

**Comment by Vunguyennhauyen** [comment]
Thiết kế giao diện trang chủ 
https://www.figma.com/design/pyvzZGQd1MXqhExEiSXAfL/Untitled?node-id=0-1&p=f&t=WZTQtm14bOrArBMj-0

**Comment by Vunguyennhauyen** [comment]
Thiết kế phần combo cho giao diện trang chủ 

https://www.figma.com/design/pyvzZGQd1MXqhExEiSXAfL/Untitled?node-id=0-1&p=f&t=WZTQtm14bOrArBMj-0

**Comment by Phongut05** [comment]
Thiết kế phần dịch vụ: 
https://www.figma.com/design/CMdeGM8ZAH4sSHFrDDLdhM/Untitled?node-id=0-1&t=rMjw9mBwsDymVEPY-1

**Comment by Trng-Ngyn** [comment]
Thiết kế Về Chúng Tôi:
https://www.figma.com/design/TNauSENP7Mdha0RtD41TNp/Untitled?node-id=0-1&t=yOaVkXqL2V9wZPcy-1
